#!/bin/bash
MYCROFT_DIR="${HOME}/.mycroft"

usage() {
    printf "Usage: %s [options] ...[skill folder]

    -h  Show this message
    -s  Silent (don't attach to PulseAudio)
    -w  Expose websocket port (8181)

" "$(basename $0)"
}

ENABLE_PULSE_AUDIO_OPTIONS="
    --device /dev/snd
    -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    -v ~/.config/pulse/cookie:/root/.config/pulse/cookie
"

WEBSOCKET_OPTIONS=
ENABLE_WEBSOCKET_OPTIONS="
    -p 8181:8181
"

while getopts "shw" OPTION; do
    case "$OPTION" in
        h) usage && exit 0;;
        s) PULSE_AUDIO_OPTIONS=;;
        w) WEBSOCKET_OPTIONS=$ENABLE_WEBSOCKET_OPTIONS;;
    esac
done

SKILL_VOLUME_OPTIONS=
while [ -n "$1" ]; do
    SKILL_VOLUME_OPTIONS="$SKILL_VOLUME_OPTIONS -v $1:/opt/mycroft/skills/$(basename $1)"
    shift
done

if [ ! -d "$MYCROFT_DIR" ]; then
    mkdir $MYCROFT_DIR
fi

docker run -d \
    $PULSE_AUDIO_OPTIONS \
    $WEBSOCKET_OPTIONS \
    $SKILL_VOLUME_OPTIONS \
    -v $MYCROFT_DIR:/root/.mycroft \
    --name mycroft \
    --rm \
    mycroftai/docker-mycroft > /dev/null

echo "Now that Mycroft is running, here is how you can interact:

Accessing Mycroft CLI
* docker exec -it mycroft /bin/bash
* ./start-mycroft.sh cli

Installing Skills on Docker Mycroft
* docker exec -it mycroft /opt/mycroft/msm/msm install github_url

Removing Skills on Docker Mycroft
* docker exec -it mycroft /opt/mycroft/msm/msm remove skill-hello-world

Scaffoling out a new skill
* docker exec -it mycroft /opt/mycroft/bin/mycroft-msk create

Stop Mycroft
* docker stop mycroft

"
