#!/bin/bash

DIRNAME=$(basename "$PWD")
CONTAINER_NAME=${DIRNAME//[[:space:]]}

echo "Serving local directory at http://localhost:8080" &&
docker run --name "$CONTAINER_NAME" -p 8080:80 -v "$(pwd):/usr/share/nginx/html" --rm nginx
