#!/bin/bash
OTR=./otr.log

printf """## ${1:-New session}

$(date)
""" >> $OTR

while read -rp "otr> " COMMAND; do
    echo """
### $COMMAND

'''""" >> $OTR

    exec $COMMAND | tee -a $OTR

    echo "'''" >> $OTR
done

echo

