#!/bin/bash
PROJECT=$1

# Resolve project to path (if not one already)
if [ -d "$PROJECT" ]; then
    PROJECT_PATH=$1
else
    PROJECT_PATH=~/Code/$PROJECT
fi

# Change to project context
cd "$PROJECT_PATH" || exit 1

# Set terminal title
echo -ne "\033]0;$(basename "$PWD")\007"

# Project-type Steps
PROJECT_TYPE=plain
if [ -f package.json ]; then
    PROJECT_TYPE=npm
    npm ci
fi

# Start editor (GUI 1st, then fail to default)
gvim || $EDITOR

# Start screen
[ ! -f .screen_layout ] && [ -f ~/.screen_layouts/$PROJECT_TYPE ] && cp ~/.screen_layouts/$PROJECT_TYPE ./.screen_layout
screen

