#!/bin/bash
PROJECT=${1:-$PWD}
START_EDITOR=true
if [ "$2" = "--no-vim" ]; then
    START_EDITOR=false
fi

# Resolve project to path (if not one already)
if [ -d "$PROJECT" ]; then
    PROJECT_PATH=$1
else
    PROJECT_PATH=~/Code/$PROJECT
fi

# Change to project context
cd "$PROJECT_PATH" || exit 1

# Set terminal title
echo -ne "\033]0;$(basename "$PWD")\007"

# Project-type Steps
PROJECT_TYPE=plain
if [ -f package.json ]; then
    PROJECT_TYPE=npm
    npm ci
elif [ -f Cargo.toml ]; then
    PROJECT_TYPE=rust
elif [ -d .git ]; then
    PROJECT_TYPE=git
fi

if [ "$START_EDITOR" = "true" ]; then
    # Start editor (GUI 1st, then fail to default)
    gvim || $EDITOR
fi

# Start screen
[ ! -f .screen_layout ] && [ -f ~/.screen_layouts/$PROJECT_TYPE ] && cp ~/.screen_layouts/$PROJECT_TYPE ./.screen_layout
screen

