#!/bin/bash
MAX_SIZE="10M"
SLEEP=1

get_sum() {
    find "$PWD" -type f -size -$MAX_SIZE -exec shasum {} ";" | shasum
}

DIRECTORY="$1"
shift
if [ ! -d "$DIRECTORY" ]; then
    echo "$DIRECTORY is not a directory"
    exit 1
fi
echo "Watching $DIRECTORY"

COMMAND="$*"
echo "Executing $COMMAND"

while true; do
    NEW_SUM=$(get_sum)

    if [ "$LAST_SUM" != "$NEW_SUM" ]; then
        eval "$COMMAND"
    fi

    LAST_SUM=$NEW_SUM
    sleep $SLEEP
done
